$:
  vscode:
    - docker:
        build: 
          dockerfile: .cnb/Dockerfile
      runner:
        cpus: 8
        tags: cnb:arch:amd64:gpu
      services:
        - vscode
        - docker
      stages:
        - name: ll
          script: ls -la
  tag_push:
    - services:
        - docker
      stages:
        - name: docker login
          script: docker login -u ${CNB_TOKEN_USER_NAME} -p "${CNB_TOKEN}" ${CNB_DOCKER_REGISTRY}
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest .
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:latest