$:
  vscode:
    - docker:
        image: docker.cnb.cool/aiedulab/library/mineru:latest
      runner:
        cpus: 16
        tags: cnb:arch:amd64:gpu:L20
      services:
        - vscode
        - docker
      stages:
        - name: ll
          script: ls -la