version: '3.8'

services:
  document-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: document-scheduler:latest
    container_name: document-scheduler
    ports:
      - "8000:8000"
    volumes:
      - ./test:/app/test:ro
      - ./output:/app/output
      - ./logs:/app/logs
      - model-cache:/root/.cache/modelscope
    environment:
      - MINERU_MODEL_SOURCE=modelscope
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

volumes:
  model-cache:
    driver: local
